dist: xenial
sudo: true

language: c

matrix:
  include:
    - os: linux
      after_success:
        - bash .ci/deploy-docs.sh

    - os: linux
      compiler: clang

    - os: osx
      install:
        - export HOMEBREW_NO_AUTO_UPDATE=1
        - export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # for the docs
        - brew install freetype fribidi gtk-doc harfbuzz

before_script:
  - ./autogen.sh
  - ./configure --enable-gtk-doc

script:
  - make check || (cat `find . -name '*.log'` && false)
  - make distcheck

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - gtk-doc-tools
